
[Languages]
[Languages.en]
title = "ArgoCD Techlab"
languageName = "English"
weight = 1


[params]
enabledModule = "base centris manual-fork no-argocd-cli openshift getting-started simple-example resource-hooks sync-phases-and-waves tools helm kustomize multiple-applications application-sets projects "
github_repo = ""
github_branch = ""
