
[Languages]
[Languages.en]
title = "ArgoCD Techlab"
languageName = "English"
weight = 1


[params]
enabledModule = "base manualFork noArgoCDCLI openshift centris"
github_repo = ""
github_branch = ""
