# argocd-training 
# Change the following parts to your current installation
# - entire Docker Build steps accordingly to the amount of different versions or tags your building TRAINING_HUGO_ENV
#   - Tags
# - Helm Target Namespace
# - Name of K8S Deployment to trigger and namespace
# - URL that gets commented on the PR
# - Secrets
#   - QUAYIO_USERNAME and QUAYIO_TOKEN must be set accordingly to your registry, existing users must have access to the repos
#   - KUBECONFIG_TEST content of the Kubeconfig File, Account must have access to the k8s namespace. It's used in the helm steps
#   - KUBECONFIG_TEST_BASE64 same as KUBECONFIG but Base64 encoded. It's used in the kubectl steps
name: Build Training and Publish

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "content *.md"
          config_file: ".markdownlint.json"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}
      - 
        name: Build Puzzle Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TRAINING_HUGO_ENV=puzzle
          push: true
          tags: |
            quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}-puzzle
      - 
        name: 'Deploy Helm Release'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'acend-argocd-training-test'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          value-files: |
            [
              "helm-chart/values.yaml"
            ]

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
      - 
        name: Redeploy acend Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-argocd-training-acend --namespace acend-argocd-training-test
      - 
        name: Redeploy Puzzle Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-argocd-training-puzzle --namespace acend-argocd-training-test
      - 
        name: Comment PR Environments in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environments: 
           * acend version <https://argocd-training-pr-${{ github.event.pull_request.number }}.training.acend.ch>
           * puzzle version <https://argocd-training-pr-${{ github.event.pull_request.number }}.k8s.puzzle.ch>