name: Build Training and Publish

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up npm for linting
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      -
        name: Lint Markdown
        run: npm ci && npm run mdlint
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build and Push latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      -
        name: Build and Push Puzzle Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TRAINING_HUGO_ENV=puzzle
          push: true
          tags: |
            quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}-puzzle
      -
        name: Run vulnerability scanner Puzzle
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/acend/argocd-training:pr-${{ github.event.pull_request.number }}-puzzle'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      -
        name: 'Deploy Helm Release'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'acend-argocd-training-test'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          value-files: |
            [
              "helm-chart/values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
      -
        name: Redeploy acend Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-argocd-training-acend --namespace acend-argocd-training-test
      -
        name: Redeploy Puzzle Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-argocd-training-puzzle --namespace acend-argocd-training-test
      -
        name: Comment PR Environments in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environments: 
           * acend version <https://argocd-training-pr-${{ github.event.pull_request.number }}.training.acend.ch>
           * puzzle version <https://argocd-training-pr-${{ github.event.pull_request.number }}.k8s.puzzle.ch>
